package tr.kontas.splitr.consumer;

import tr.kontas.splitr.dto.QueryResponse;

/**
 * Strategy interface for managing the idempotency of distributed queries.
 * <p>
 * This store prevents the redundant execution of identical queries by caching
 * the results of previously processed correlation IDs.
 * </p>
 *
 * @author BurakKontas
 * @version 1.0.0
 */
public interface IdempotencyStore {

    /**
     * Checks if a specific query correlation ID has already been processed.
     *
     * @param id The unique correlation ID of the query.
     * @return {@code true} if the result exists in the store, {@code false} otherwise.
     */
    boolean contains(String id);

    /**
     * Retrieves the cached response for a given correlation ID.
     *
     * @param id The unique correlation ID.
     * @return The {@link QueryResponse} associated with the ID, or {@code null} if not found.
     */
    QueryResponse get(String id);

    /**
     * Persists a query result to the store.
     *
     * @param id The unique correlation ID.
     * @param r  The response generated by a {@link QueryHandler}.
     */
    void put(String id, QueryResponse r);
}